openapi: "3.0.0"
info:
  version: 1.0.0
  title: Meditation
paths:
  /meditations:
    get:
      summary: List all meditations
      operationId: getMeditations
      tags:
        - meditations
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time
          required: false
      responses:
        '200':
          description: A paged array of meditations
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meditations"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a meditation
      operationId: createMeditations
      tags:
        - Meditation
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /meditations/{meditationId}:
    get:
      summary: Info for a specific meditation
      operationId: getMeditationById
      tags:
        - meditations
      parameters:
        - name: meditationId
          in: path
          required: true
          description: The id of the meditation to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meditation"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Edit a meditation
      operationId: editMeditationById
      tags:
        - Meditation
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete a meditation
      operationId: deleteMeditationById
      tags:
        - Meditation
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Meditation:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        summary:
          type: string
        script:
          type: string
    Meditations:
      type: array
      items:
        $ref: "#/components/schemas/Meditation"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string